#!/bin/bash

./app-start && \
docker container exec web php -r 'echo `cd /var/www/app && chown -R www-data:www-data .`;' && \
docker container exec web php -r 'echo `cd /var/www/app && rm -rf node_modules && npm cache clear --force && npm install && npm run prod `;' && \
docker container exec web php -r 'echo `cd /var/www/app && composer clear-cache && composer install --no-dev  && php artisan migrate`;'
