#!/bin/bash
yum update -y && yum upgrade -y && \
yum remove -y docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine && \
yum install -y yum-utils device-mapper-persistent-data lvm2 php && \
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
yum install -y docker-ce docker-ce-cli containerd.io && \
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
sudo chmod +x /usr/local/bin/docker-compose && \
systemctl enable firewalld && systemctl start firewalld && \
firewall-cmd --zone=public --add-service=http --permanent && \
firewall-cmd --zone=public --add-service=https --permanent && \
firewall-cmd --reload && \
systemctl enable docker && systemctl start docker && \
./app-install
